"""
Django settings for clothes_shop project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4tnw9q$#rf%pp0whkza0z$ogf49ti)$u2ju)yc2g@1^js+gd0u"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost", "localhost:800"]


# Application definition

INSTALLED_APPS = [
   "django.contrib.admin",
   "django.contrib.auth",
   "django.contrib.contenttypes",
   "django.contrib.sessions",
   "django.contrib.messages",
   "django.contrib.staticfiles",
   "django_extensions",
   'django.contrib.sites',
   'allauth',
   'allauth.account',
   'allauth.socialaccount',
   'allauth.socialaccount.providers.github',
   "main",
   "users",
   'cart',
]

MIDDLEWARE = [
   "django.middleware.security.SecurityMiddleware",
   "django.contrib.sessions.middleware.SessionMiddleware",
   "django.middleware.common.CommonMiddleware",
   "django.middleware.csrf.CsrfViewMiddleware",
   "django.contrib.auth.middleware.AuthenticationMiddleware",
   "django.contrib.messages.middleware.MessageMiddleware",
   "django.middleware.clickjacking.XFrameOptionsMiddleware",
   "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "clothes_shop.urls"

TEMPLATES = [
   {
       "BACKEND": "django.template.backends.django.DjangoTemplates",
       "DIRS": [
           BASE_DIR / "templates"
       ],
       "APP_DIRS": True,
       "OPTIONS": {
           "context_processors": [
               "django.template.context_processors.debug",
               "django.template.context_processors.request",
               "django.contrib.auth.context_processors.auth",
               "django.contrib.messages.context_processors.messages",
           ],
       },
   },
]

WSGI_APPLICATION = "clothes_shop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
   "default": {
       "ENGINE": "django.db.backends.sqlite3",
       "NAME": BASE_DIR / "db.sqlite3",
   }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
   {
       "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
   },
   {
       "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
   },
   {
       "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
   },
   {
       "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
   },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
   BASE_DIR / "main/static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGOUT_REDIRECT_URL = "main_page"
LOGIN_URL = "users:login"

AUTHENTICATION_BACKENDS = [
   'django.contrib.auth.backends.ModelBackend',
   'users.authentication.EmailAuthBackend',
   'allauth.account.auth_backends.AuthenticationBackend',
]

from clothes_shop.config import YANDEX_PASSWORD, YANDEX_EMAIL, GITGUB_KEY, GITHUB_SECRET_KEY

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = YANDEX_EMAIL
EMAIL_HOST_PASSWORD = YANDEX_PASSWORD
EMAIL_USE_SSL = True

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

LOGIN_REDIRECT_URL = '/'
SITE_ID = 1

SOCIAL_AUTH_GITHUB_KEY = GITGUB_KEY
SOCIAL_AUTH_GITHUB_SECRET = GITHUB_SECRET_KEY
SOCIALACCOUNT_LOGIN_ON_GET = True

SECURE_SSL_REDIRECT = False